### ISSUE TITLE
HMC8043 - Reading StatusRegister may run into time-out

### ISSUE THREAD

**Issue by JLeib-IISB** [Rohde-Schwarz/RsInstrument#10]
Using HMC8043 with pyvisa '1.11.3'

In: lab.device.query("*IDN?")
Out: 'Rohde&Schwarz,HMC8043,053115259,HW42000000,SW01.400'

Issue: Checking Status Condition - testing on CV and CC 

Good news = **Using short version of commends is working fine**
In: lab.device.query("STAT:QUES:INST:ISUM1:COND?")
Out: '0'

Bad news = NOT working = **Using long versions of commands runs into time out**
In: lab.device.query("STATus:QUEStionable:INSTrument:ISUMmary1:CONDition?")
Out: pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.

All the best 
Juergen

P.S. By the way ... the long version is running fine on HMP4040 ...

**Comment by Miloslav-RS** [comment]
Hi Jürgen,

sorry for the delay...
Thx for reporting this, the issue is instrument-related, I am forwarding it to our development team.
