### ISSUE TITLE
Make RsInstrument usable with context managers

### ISSUE THREAD

**Issue by swaldhoer** [Rohde-Schwarz/RsInstrument#11]
Make ``RsInstrument`` usable with context managers.
This would make it more safe to communicate with an instrument and do the
cleanup work in case an error happens in the Python code.

Instead of written (example from the [docs](https://rsinstrument.readthedocs.io/en/latest/StepByStepGuide.html#standard-session-initialization)):

```python
import RsInstrument
instr = RsInstrument.RsInstrument("TCPIP::192.168.2.101::INSTR")
idn = instr.query_str('*IDN?')
# do something with the instrument that might fail - close will **not** be called
instr.close()
```

In that case the resource is not cleaned up.
Using a context manager the resource would be cleaned up:

```python
import RsInstrument
with RsInstrument.RsInstrument("TCPIP::192.168.2.101::INSTR") as instr:
    idn = instr.query_str('*IDN?')
    # do something with the instrument that might fail - close will be called anyway!
```

Until now I had no look into the code, but maybe something like this is
sufficient:

```python
class RsInstrument:
    def __init__(self, ...):
        pass # as the current implantation

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_value, exc_traceback):
        self.close()
```

**Comment by Miloslav-RS** [comment]
Good idea, will come out with the next version 1.55

**Comment by Miloslav-RS** [comment]
The version 1.55 with the context manager interface is out...
