### ISSUE TITLE
VisaLib.read method in the "RsInstrument\Internal\VisaPluginSocketIo.py" hangs infinitely if socket ends (e.g. server crashes)

### ISSUE THREAD

**Issue by mkrugly** [Rohde-Schwarz/RsInstrument#14]
In case the socket ends e.g. due to the server crash the VisaLib.read method never finishes, because it's _while_ loop never breaks.
The solution would be to break the loop (or raise Exception) if `session.recv(to_read_len)` returns no data

**Comment by Miloslav-RS** [comment]
This will be fixed in the upcoming version 1.56

**Comment by Miloslav-RS** [comment]
Fixed in the released version 1.60.0
