### ISSUE TITLE
PyVISA-py support?

### ISSUE THREAD

**Issue by oberstet** [Rohde-Schwarz/RsInstrument#15]
Hi there,

quick Q: are there any plans for **RsInstrument** to support running on top of [PyVISA-py](https://github.com/pyvisa/pyvisa-py) without a proprietary IVI-VISA library installed, such as *R&S®VISA* or others?

As far as I understand (I'm new to this stuff, so I might have overlooked/misunderstood sth, pls correct me if so ..):

*R&S®VISA* is proprietary freeware, shipped as a native blob with associated annoyances and potential for increased security attack surface, and is unconditionally _required_ to make any practical use of **RsInstrument**, right?

Thanks!

**Comment by Miloslav-RS** [comment]
Hi oberstet, sorry, for the late answer, use the LAN plain Socket: https://rsinstrument.readthedocs.io/en/latest/StepByStepGuide.html#no-visa-session

**Comment by oberstet** [comment]
Thanks for answering! So the answer is "no", and I am wondering, why I would want to use **RsInstrument** just for a plain, raw TCP socket connection. What's the point? Well, what's the point of forcing proprietary R&S®VISA blobs onto developers. Anyways. Won't happen. Waste of time.

**Comment by Miloslav-RS** [comment]
Sorry to force the RsInstrument on you :-) Pyvisa-py is also an additional software layer, which I see you want to avoid. But the answer is 'YES', use the SelectVisa='@py' in the options string:

io = RsInstrument("TCPIP::192.168.52.102", options="SelectVisa=@py")

**Comment by oberstet** [comment]
> Sorry to force the RsInstrument on you :-)

=) No worries! I understand. "Trying" is ok. I will just ignore that. 

FWIW, luckily I only need to deal with RF sub 6 GHz, I don't need top-end hardware like R&S provides, and I found a VNA which is fully OSS (both HW and all SW, including firmware and user libs, no BLOBs!) - and supports Python;)
