### ISSUE TITLE
The Instrument looses its calibration as soon as I start my Code?

### ISSUE THREAD

**Issue by julisity** [Rohde-Schwarz/RsInstrument#6]
Hey there, so my Code correctly eads out the four S-Params of  a ZNB20, but if the Insrument is callibrated before, it looses its calibration. This makes the measurement very inaccurate. How can i solve this? 
Thanks for your help in advance!
The code is proved here:
https://github.com/julisity/Rohde_schwarz-read-out

**Comment by Miloslav-RS** [comment]
Hi julisity,

sorry for the delay, we forgot to monitor the repositories.
This is a ZNB-related problem, I hope our customer support was able to help you. Closing the issue.

BR
Milo
