### ISSUE TITLE
How can I set GNSS coordinates to SMBV100B using this library?

### ISSUE THREAD

**Issue by leonardobotarelli** [Rohde-Schwarz/RsInstrument#8]
Is it possible to set GNSS coordinates to SMBV100B using this library, through python?
I was successful when trying to control frequency and power, however I was not able to set arbitrary GNSS coordinates.
Can you please support?
Thank you very much!

**Comment by Miloslav-RS** [comment]
Hi Leonardo,

sorry for the delay...
Sure, please contact our customer support, they will provide you with the SCPI sequences.
